[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

  [plugins.build]
  windows = 'tools\\update-dll-mingw'
  cygwin  = 'make -f make_cygwin.mak'
  mac     = 'make -f make_mac.mak'
  linux   = 'make'
  unix    = 'gmake'

[[plugins]]
repo = 'Shougo/unite.vim'
on_path = '.*'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'pyohei/vim-pyimporter'

[[plugins]]
repo = 'pyohei/vim-bunshin'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'vim-scripts/Align'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'JulesWang/css.vim'

[[plugins]]
repo = 'gorodinskiy/vim-coloresque'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'mhartington/oceanic-next'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'glidenote/memolist.vim'

[[plugins]]
repo = 'lambdalisue/vim-gita'

[[plugins]]
repo = 'davidhalter/jedi-vim'

[[plugins]]
repo = 'tell-k/vim-autopep8'

[[plugins]]
repo = 'vim-ruby/vim-ruby'

[[plugins]]
repo = 'koron/dicwin-vim'
